target: hw4_Series.c hw4_Pi.c gnerate.c
	g++ -Wall -o hw4_Series hw4_Series.c -lpthread
	g++ -Wall -o hw4_Pi hw4_Pi.c -lpthread
	gcc -o gnerate gnerate.c
	./gnerate
clean:
	rm hw4_Series hw4_Pi gnerate input.txt
